export const LOGIN = "LOGIN";
export const LOGIN_LOADER = "LOGIN_LOADER";
export const STUDENTS_LOADING = "STUDENTS_LOADING";
export const ADMIN_LOADING = "ADMIN_LOADING";
export const REGISTER_LOADER = "REGISTER_LOADER";
export const LOGOUT = "LOGOUT";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const ADD_CERTIFICATIONS_LOADER = "ADD_CERTIFICATIONS_LOADER";
export const EDIT_STUDENT_LOADING = "EDIT_STUDENT_LOADING";
export const DELETE_STUDENT_LOADING = "DELETE_STUDENT_LOADING";
export const GET_JOBS = "GET_JOBS";

export const ADD_LOADER = "ADD_LOADER";
export const ADD_COURSE_LOADER = "ADD_COURSE_LOADER";
export const ADD_JOB_LOADER = "ADD_JOB_LOADER";
export const ADD_QUESTIONS_LOADER = "ADD_QUESTIONS_LOADER";
export const GET_COURSES = "GET_COURSES";
export const GET_CERTIFICATIONS = "GET_CERTIFICATIONS";
export const GET_MAJORS = "GET_MAJORS";
export const GET_LOADER = "GET_LOADER";
export const GET_JOB_LOADER = "GET_JOB_LOADER";
export const GET_CERTIFICATIONS_LOADER = "GET_CERTIFICATIONS_LOADER";
export const DELETE_CERTIFICATIONS_LOADER = "DELETE_CERTIFICATIONS_LOADER";
export const COURSE_LOADING = "COURSE_LOADING";

export const AUTH_SET_LOADING = "AUTH_SET_LOADING";
export const AUTH_NOTIFICATION = "AUTH_NOTIFICATION";
export const GET_ADMIN = "GET_ADMIN";
export const GET_QUESTIONS = "GET_QUESTIONS";
export const GET_QUESTIONS_LOADER = "GET_QUESTIONS_LOADER";
export const GET_STUDENT = "GET_STUDENT";
export const GET_ACADEMIC_PROGRESS = "GET_ACADEMIC_PROGRESS";


export const GET_GRADE_FACTOR = "GET_GRADE_FACTOR"
